name: owdfa
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=3.0.0
  - async-lru=2.0.4
  - attrs=24.3.0
  - babel=2.16.0
  - bleach=6.2.0
  - brotli-python=1.1.0
  - brotlicffi=1.0.9.2
  - ca-certificates=2025.7.14
  - cffi=1.17.1
  - comm=0.2.3
  - debugpy=1.8.15
  - defusedxml=0.7.1
  - dlib=19.24.2
  - executing=2.2.0
  - h2=4.2.0
  - hpack=4.1.0
  - httpx=0.28.1
  - hyperframe=6.1.0
  - idna=3.10
  - importlib-metadata=8.7.0
  - ipykernel=6.29.5
  - ipython=8.18.1
  - jedi=0.19.2
  - json5=0.9.25
  - jsonschema=4.25.0
  - jsonschema-specifications=2023.7.1
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - jupyter_events=0.12.0
  - jupyter_server=2.16.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.4.4
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - keyutils=1.6.1
  - krb5=1.21.3
  - ld_impl_linux-64=2.40
  - libblas=3.9.0
  - libcblas=3.9.0
  - libedit=3.1.20191231
  - libffi=3.4.4
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgfortran=14.2.0
  - libgfortran5=14.2.0
  - libgomp=14.2.0
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libopenblas=0.3.28
  - libpng=1.6.43
  - libsodium=1.0.20
  - libsqlite=3.46.0
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libzlib=1.2.13
  - matplotlib-inline=0.1.7
  - mistune=3.1.2
  - nbclient=0.10.2
  - nbconvert-core=7.16.6
  - nbformat=5.10.4
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - notebook-shim=0.2.4
  - numpy=1.26.4
  - openssl=3.5.1
  - overrides=7.4.0
  - p7zip=16.02
  - pandocfilters=1.5.0
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=24.2
  - prometheus_client=0.21.1
  - prompt-toolkit=3.0.51
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pycparser=2.21
  - pysocks=1.7.1
  - python=3.9.21
  - python-dateutil=2.9.0.post0
  - python-fastjsonschema=2.20.0
  - python-json-logger=3.2.1
  - python_abi=3.9
  - pyyaml=6.0.2
  - pyzmq=27.0.0
  - readline=8.2
  - referencing=0.30.2
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.22.3
  - send2trash=1.8.2
  - setuptools=75.1.0
  - six=1.17.0
  - sniffio=1.3.1
  - sqlite=3.45.3
  - stack_data=0.6.3
  - terminado=0.17.1
  - tinycss2=1.4.0
  - tk=8.6.14
  - tomli=2.2.1
  - tornado=6.5.1
  - traitlets=5.14.3
  - wcwidth=0.2.13
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.44.0
  - xz=5.4.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zlib=1.2.13
  - zstandard=0.23.0
  - pip:
      - aiofiles==23.2.1
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.11.11
      - aiosignal==1.3.2
      - albucore==0.0.23
      - albumentations==2.0.0
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.8.0
      - async-timeout==5.0.1
      - beautifulsoup4==4.12.3
      - better-exceptions==0.3.3
      - blurhash==1.1.4
      - boost==0.1
      - certifi==2024.12.14
      - charset-normalizer==3.4.1
      - click==8.1.8
      - cmake==3.31.4
      - contourpy==1.3.0
      - cycler==0.12.1
      - datasets==4.4.1
      - decorator==5.1.1
      - decord==0.6.0
      - dill==0.4.0
      - distro==1.9.0
      - docker-pycreds==0.4.0
      - easydict==1.13
      - eval-type-backport==0.2.2
      - exceptiongroup==1.2.2
      - fastapi==0.115.6
      - ffmpy==0.5.0
      - filelock==3.16.1
      - fonttools==4.55.3
      - frozenlist==1.5.0
      - fsspec==2024.12.0
      - gdown==5.2.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - gradio==4.44.1
      - gradio-client==1.3.0
      - greenlet==3.1.1
      - h11==0.14.0
      - httpcore==1.0.7
      - huggingface-hub==0.27.1
      - imageio==2.37.0
      - importlib-resources==6.5.2
      - imutils==0.5.4
      - jinja2==3.1.5
      - joblib==1.4.2
      - kiwisolver==1.4.7
      - kneed==0.8.5
      - lazy-loader==0.4
      - lightning==2.2.5
      - lightning-utilities==0.11.9
      - lmdb==1.6.2
      - loguru==0.7.3
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - mastodon-py==1.8.1
      - matplotlib==3.9.4
      - mdurl==0.1.2
      - mpmath==1.3.0
      - multidict==6.1.0
      - multiprocess==0.70.18
      - networkx==3.2.1
      - nvidia-cublas-cu11==11.11.3.6
      - nvidia-cuda-cupti-cu11==11.8.87
      - nvidia-cuda-nvrtc-cu11==11.8.89
      - nvidia-cuda-runtime-cu11==11.8.89
      - nvidia-cuda-runtime-cu12==12.9.79
      - nvidia-cudnn-cu11==8.7.0.84
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.3.0.86
      - nvidia-cusolver-cu11==11.4.1.48
      - nvidia-cusparse-cu11==11.7.5.86
      - nvidia-nccl-cu11==2.20.5
      - nvidia-nvtx-cu11==11.8.86
      - omegaconf==2.3.0
      - onnx==1.17.0
      - opencv-python-headless==4.11.0.86
      - opentsne==1.0.2
      - orjson==3.10.15
      - packaging==24.2
      - pandas==2.2.3
      - pillow==10.4.0
      - platformdirs==4.3.6
      - propcache==0.2.1
      - protobuf==5.29.3
      - psutil==6.1.1
      - pyarrow==21.0.0
      - pydantic==2.10.5
      - pydantic-core==2.27.2
      - pydub==0.25.1
      - pygments==2.19.1
      - pyparsing==3.2.1
      - python-magic==0.4.27
      - python-multipart==0.0.20
      - pytorch-lightning==2.2.5
      - pytorch-metric-learning==2.8.1
      - pytorch-ranger==0.1.1
      - pytz==2024.2
      - requests==2.32.3
      - rich==13.9.4
      - ruff==0.9.2
      - scikit-build==0.18.1
      - scikit-image==0.24.0
      - scikit-learn==1.6.1
      - scipy==1.13.1
      - seaborn==0.13.2
      - semantic-version==2.10.0
      - sentry-sdk==2.20.0
      - setproctitle==1.3.4
      - shellingham==1.5.4
      - simsimd==6.2.1
      - smmap==5.0.2
      - soupsieve==2.6
      - sqlalchemy==2.0.37
      - starlette==0.41.3
      - stringzilla==3.11.3
      - sympy==1.13.3
      - tensorboardx==2.6.2.2
      - tensorrt==10.7.0
      - tensorrt-cu12==10.7.0
      - tensorrt-cu12-bindings==10.7.0
      - tensorrt-cu12-libs==10.7.0
      - threadpoolctl==3.5.0
      - tifffile==2024.8.30
      - timm==0.4.12
      - tomlkit==0.12.0
      - torch==2.3.1+cu118
      - torch-dct==0.1.6
      - torch-optimizer==0.3.0
      - torchaudio==2.3.1+cu118
      - torchmetrics==1.5.2
      - torchvision==0.18.1+cu118
      - tqdm==4.67.1
      - triton==2.3.1
      - ttach==0.0.3
      - typer==0.15.1
      - typing-extensions==4.12.2
      - tzdata==2024.2
      - urllib3==2.3.0
      - uvicorn==0.34.0
      - wandb==0.19.4
      - websockets==12.0
      - xxhash==3.6.0
      - yarl==1.18.3
      - zipp==3.21.0
